-- ============================================
-- Adhoc Student Helper - Supabase Schema
-- ============================================

-- Drop existing table and policies if they exist (to start fresh)
DROP POLICY IF EXISTS "Allow public insert" ON infogram_logs;
DROP POLICY IF EXISTS "Allow public select" ON infogram_logs;
DROP TABLE IF EXISTS infogram_logs;

-- Create the infogram_logs table
CREATE TABLE infogram_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  file_name TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  infogram_data TEXT NOT NULL,
  sketch_image_data TEXT
);

-- Create indexes for better performance
CREATE INDEX idx_infogram_logs_created_at ON infogram_logs(created_at DESC);
CREATE INDEX idx_infogram_logs_title ON infogram_logs(title);
CREATE INDEX idx_infogram_logs_difficulty ON infogram_logs(difficulty);

-- Enable Row Level Security
ALTER TABLE infogram_logs ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (no authentication required)
-- Policy 1: Allow anyone to insert
CREATE POLICY "Enable insert for all users" ON infogram_logs
  FOR INSERT 
  WITH CHECK (true);

-- Policy 2: Allow anyone to select
CREATE POLICY "Enable select for all users" ON infogram_logs
  FOR SELECT 
  USING (true);

-- Policy 3: Allow anyone to update (optional, for future features)
CREATE POLICY "Enable update for all users" ON infogram_logs
  FOR UPDATE 
  USING (true);

-- Add comments for documentation
COMMENT ON TABLE infogram_logs IS 'Stores educational infograms generated by Adhoc Student Helper';
COMMENT ON COLUMN infogram_logs.id IS 'Unique identifier for the infogram';
COMMENT ON COLUMN infogram_logs.created_at IS 'Timestamp when the infogram was created';
COMMENT ON COLUMN infogram_logs.file_name IS 'Original PDF filename';
COMMENT ON COLUMN infogram_logs.title IS 'Generated infogram title';
COMMENT ON COLUMN infogram_logs.summary IS 'Brief summary of the content';
COMMENT ON COLUMN infogram_logs.difficulty IS 'Difficulty level: Básico, Intermedio, or Avanzado';
COMMENT ON COLUMN infogram_logs.infogram_data IS 'Complete infogram data in JSON format';
COMMENT ON COLUMN infogram_logs.sketch_image_data IS 'Base64 encoded sketch notes image';

-- Grant permissions to anon and authenticated roles
GRANT ALL ON infogram_logs TO anon;
GRANT ALL ON infogram_logs TO authenticated;

-- Success message
DO $$
BEGIN
  RAISE NOTICE '✅ Table "infogram_logs" created successfully with public access policies!';
END $$;
